Обратная сторона реальности
htmlacademy-react/1110353-six-cities-10 pull request #5
Opened 2022-07-19 13:42 UTC by AnastasiaRakh3

---
:mortar_board: [Обратная сторона реальности](https://up.htmlacademy.ru/react/10/user/1110353/tasks/6)

2022-07-22 10:33 UTC, ValeriiMakhniuk commented on project/src/pages/room-screen/room-screen.tsx
> +  const { id } = useParams();
Тут `id`, как правильно подсказывает typescript, можеть быть `string | undefined`. `indefined` может быть в тому случае, если на этот роут юзер попал не програмно(через твои вызовы `navigate()` или через `<Link />`), а через url строку бразуера. К примеру если они забыл доавить параметр или ввел рандомный. Поэтому мы можешь сделать проверку на то что `id`

2022-07-22 10:41 UTC, ValeriiMakhniuk commented on project/src/pages/room-screen/room-screen.tsx
> +  const room = offersList.find((offer: Offer) => offer.id === +id!) as Offer;
Оператор `as` может сыграть с тобой злую шутку если в `url` юзер передаст `id` офера, которого нет в моках. Тут ты явно говоришь typescript, что ты уверена что офер с `id` из урла точно будет найден в моих моках. Но мы никогда не должны доверять пользователю в таких случаях.

Лучше, как я описал выше с `id` в `url` сделать проверку что оффер найден в `offersList` а если нет редирекнуть на `404` страницу. Или же объеденить эти 2 проверки между собой, чтобы не писать больше кода.

2022-07-22 10:51 UTC, ValeriiMakhniuk commented on project/src/utils.ts
> +const isPremium = (offer: Offer, place: string) =>
Твоя функция возвращает строку, что не является React элементом, поэтому React рендерит это как обычную строку. Можешь посмотреть, как сейчас выгляит `premium` оффер на главной странице.
Ты можешь сделать расщирение у файла `.tsx` и возвращать `JSX` либо сделать эту проверку у компонента ``

2022-07-22 11:00 UTC, ValeriiMakhniuk commented on project/src/components/places-list/places-list.tsx
> +          handlePlaceCardMouseOver={(evt) => setActiveOffer(offer)}
функции обработчики передаваемы в пропсы должны начинатся с `on`(https://up.htmlacademy.ru/react/10/criteries#d9). То есть `onPlaceCardMouseOver`. А вот как раз обработчик должне нахываться через `handle`. И лучше не объявлять функцию обработчик в пропсах, а создать отдельно в теле компонента `<PlacesList />`

2022-07-22 11:11 UTC, ValeriiMakhniuk commented on project/src/components/favorite-card/favorite-card.tsx
> +          <Link to={`${AppRoute.Room}${offer.id}`}>{offer.title}</Link>
У тебя тут ошибка в `path`

2022-07-22 11:14 UTC, ValeriiMakhniuk commented on project/src/components/place-card/place-card.tsx
> +          <Link to={`${AppRoute.Room}${offer.id}`}>{offer.title}</Link>
Тут тоже ошибка в пути

2022-07-22 11:35 UTC, ValeriiMakhniuk commented on project/src/components/review-form/review-form.tsx
> +  const ratingTitle: ratingTitleType = {
Эту константу лучше вынести на уровень констант, так как она не меняется динамически и не требует пересоздания во время рендера/ререндера компонента

2022-07-22 11:37 UTC, ValeriiMakhniuk commented on project/src/components/review-form/review-form.tsx
> +                  onClick={() => setReview({ ...review, rating: starNumber })}
Лучше не "инлайнить" функции обработчики, а деклалировать их в теле компонента выше и передавать в качестве props методов `on...`, чтобы было удобно и если что их можно будет мемоизировать в будующем. А так у тебя на кажде изменения создлается новая функция с одним и темже йункционалом.

2022-07-22 11:40 UTC, ValeriiMakhniuk commented on project/src/pages/favorites-screen/favorites-screen.tsx
> +            {isFavoritesAdded}
Тут не совсем понятно, что в константе `isFavoritesAdded` лежит `JSX`. На мой взгляд было бы лучше перенсти проверку прямо сюда и использовтаь условный рендеринг что ты сейчас и делаешь в константе. Либо оставить только проверку чтобы было семантично и понятно по именованию а здесь уже опираясь на значение константы `isFavoritesAdded` рисовать нужный `JSX`

2022-07-22 11:42 UTC, ValeriiMakhniuk commented on project/src/pages/room-screen/room-screen.tsx
> +  const commentElements = reviews.map(
Было бы круто сделать отдлеьный компонент `<Comment />`. Но можем оставить на будущее

2022-07-22 16:20 UTC, ValeriiMakhniuk requested changes
Все хорошо, ты молодец!
Нужны мелкие правки

2022-07-23 08:16 UTC, AnastasiaRakh3 commented on project/src/utils.ts
> +const isPremium = (offer: Offer, place: string) =>
Done

2022-07-23 08:26 UTC, AnastasiaRakh3 commented on project/src/components/places-list/places-list.tsx
> +          handlePlaceCardMouseOver={(evt) => setActiveOffer(offer)}
Пока не создавала отдельно функцию обработчик, так как нужен offer
Исправила

2022-07-23 08:35 UTC, AnastasiaRakh3 commented on project/src/components/favorite-card/favorite-card.tsx
> +          <Link to={`${AppRoute.Room}${offer.id}`}>{offer.title}</Link>
Не заметила даже(
Интересно почему работало все равно без ошибки, ранее вбивала / (ex. 3000/offer/1) и все работало 
Исправила

2022-07-23 08:35 UTC, AnastasiaRakh3 commented on project/src/components/place-card/place-card.tsx
> +          <Link to={`${AppRoute.Room}${offer.id}`}>{offer.title}</Link>
Done

2022-07-23 08:43 UTC, AnastasiaRakh3 commented on project/src/components/review-form/review-form.tsx
> +  const ratingTitle: ratingTitleType = {
Done

2022-07-23 09:09 UTC, AnastasiaRakh3 commented on project/src/pages/favorites-screen/favorites-screen.tsx
> +            {isFavoritesAdded}
Попробовала переименовать константу
Хочется вынести все изменяемое пока в отдельные проверки, чтобы понимать, что может измениться, если так можно)

2022-07-23 09:09 UTC, AnastasiaRakh3 commented on project/src/pages/room-screen/room-screen.tsx
> +  const commentElements = reviews.map(
Done

2022-07-23 09:35 UTC, AnastasiaRakh3 commented on project/src/pages/room-screen/room-screen.tsx
> +  const { id } = useParams();
Done

2022-07-23 09:35 UTC, AnastasiaRakh3 commented on project/src/pages/room-screen/room-screen.tsx
> +  const room = offersList.find((offer: Offer) => offer.id === +id!) as Offer;
Done

2022-07-23 09:35 UTC, AnastasiaRakh3 commented on project/src/components/review-form/review-form.tsx
> +                  onClick={() => setReview({ ...review, rating: starNumber })}
Пока не исправила

2022-07-23 11:56 UTC, ValeriiMakhniuk commented on project/src/components/review-form/review-form.tsx
> +                  onClick={() => setReview({ ...review, rating: starNumber })}
Видел твой вопрос в телеге. Отвечу тут:
Я не угялдел что ты внутри `.map()` прокидываешь функцию. Впринципе, ты можешь оставить как есть. Есть еще вариант с использованием замыкания, чтобы объявить в теле компонента:
```
handleRatingSelect = (starNumber) => () => {
    setReview({...review, rating: starNumber})
}
```
Если так сделаешь, думаю, разберешься как использовтаь внутри `.map()`

2022-07-23 11:58 UTC, ValeriiMakhniuk commented on project/src/pages/login-screen/login-screen.tsx
>                <a className="header__logo-link" href="main.html">
Тут можешь использовать `Link` из `react-router`, чтобы напралвять на `/`

2022-07-23 12:16 UTC, ValeriiMakhniuk requested changes
Все отлично! Нужно немножко доработать.

2022-07-23 12:33 UTC, ValeriiMakhniuk commented on project/src/components/places-list/places-list.tsx
> +          onPlaceCardMouseOver={() => setActiveOffer(offer)}
Вообще, раз у тебя тут компонент, ты можешь прокинуть проп `setActiveOffer={setActiveOffer}`, а внутри компонента уже навесить обработчик `onMouseOver` из сделать `handleMouseOver` обработчик в котором уже будешь делать оффер активным

2022-07-23 12:35 UTC, ValeriiMakhniuk requested changes
Это последний коммент

2022-07-24 13:48 UTC, merged